name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: make dep
      run: make dep

    - name: Test
      run: make test
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
   
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.48
